contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #sentieon channel"
    url: https://nfcore.slack.com/channels/sentieon
    about: Discussion about the nf-core/sentieon pipeline
